// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg5uvZ3I2UCIUP2ok9CXmdKXJY1Sl6-Wc',
    appId: '1:216337217404:web:f12f67c3f90e3ad72056f9',
    messagingSenderId: '216337217404',
    projectId: 'gridrnd-fda43',
    authDomain: 'gridrnd-fda43.firebaseapp.com',
    storageBucket: 'gridrnd-fda43.appspot.com',
    measurementId: 'G-6ZTL6H050J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOlW_QwlC-r_tx7nUHvwAdqEQ258tIFuc',
    appId: '1:216337217404:android:c0d6a775cbbcafbc2056f9',
    messagingSenderId: '216337217404',
    projectId: 'gridrnd-fda43',
    storageBucket: 'gridrnd-fda43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZM1I0efY7nDdQ98u6tZ_qCCidzePdQ3g',
    appId: '1:216337217404:ios:7f42e51ad8cf28732056f9',
    messagingSenderId: '216337217404',
    projectId: 'gridrnd-fda43',
    storageBucket: 'gridrnd-fda43.appspot.com',
    iosBundleId: 'com.example.gridrnd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZM1I0efY7nDdQ98u6tZ_qCCidzePdQ3g',
    appId: '1:216337217404:ios:7f42e51ad8cf28732056f9',
    messagingSenderId: '216337217404',
    projectId: 'gridrnd-fda43',
    storageBucket: 'gridrnd-fda43.appspot.com',
    iosBundleId: 'com.example.gridrnd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg5uvZ3I2UCIUP2ok9CXmdKXJY1Sl6-Wc',
    appId: '1:216337217404:web:cb86464b655b40212056f9',
    messagingSenderId: '216337217404',
    projectId: 'gridrnd-fda43',
    authDomain: 'gridrnd-fda43.firebaseapp.com',
    storageBucket: 'gridrnd-fda43.appspot.com',
    measurementId: 'G-8L1C8Z9F8G',
  );
}
